name: External Test

on:
  push:
    branches:
      - master
      - '**/test**'
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test_wasm_learning:
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu2004_x86_64
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        rustwasmc-options: ['', '--enable-aot']

    steps:
    - uses: actions/checkout@v2

    - name: Checkout wasm-learning
      uses: actions/checkout@v2
      with:
        repository: second-state/wasm-learning
        path: wasm-learning

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set Rust to required version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.50.0
        override: true

    - name: Install dependencies
      run: |
        npm install --unsafe-perm -g rustwasmc
        chmod a+w /github/home/.profile

    - name: Build and install wasmedge-core
      uses: './.github/actions/build-from-source'

    - name: Test functions ${{ matrix.rustwasmc-options }}
      run: |
        rustwasmc build ${{ matrix.rustwasmc-options }}
        cd pkg && npm install --unsafe-perm ${GITHUB_WORKSPACE} && cd ..
        . $HOME/.wasmedge/env && node node/app.js
        rustwasmc clean
      working-directory: wasm-learning/nodejs/functions

    - name: Test JSON IO ${{ matrix.rustwasmc-options }}
      run: |
        rustwasmc build ${{ matrix.rustwasmc-options }}
        cd pkg && npm install --unsafe-perm ${GITHUB_WORKSPACE} && cd ..
        . $HOME/.wasmedge/env && node node/app.js
        rustwasmc clean
      working-directory: wasm-learning/nodejs/json_io

    - name: Test WASI ${{ matrix.rustwasmc-options }}
      run: |
        rustwasmc build ${{ matrix.rustwasmc-options }}
        cd pkg && npm install --unsafe-perm ${GITHUB_WORKSPACE} && cd ..
        . $HOME/.wasmedge/env && node node/app.js
        rustwasmc clean
      working-directory: wasm-learning/nodejs/wasi

    - name: Test KMeans ${{ matrix.rustwasmc-options }}
      if: ${{ contains(matrix.rustwasmc-options, 'aot') }}
      run: |
        rustwasmc build ${{ matrix.rustwasmc-options }}
        cd pkg && npm install --unsafe-perm ${GITHUB_WORKSPACE} && cd ..
        cd node
        . $HOME/.wasmedge/env && node app.js
        cd -
        rustwasmc clean
      working-directory: wasm-learning/nodejs/kmeans
