name: Main Workflow

on:
  push:
    branches:
    - master
    - '**/test**'
  pull_request:
    branches:
    - master

jobs:
  build_and_test:
    strategy:
      matrix:
        include:
        - cc: 'clang'
          cxx: 'clang++'
        - cc: 'gcc'
          cxx: 'g++'
    name: Build & test wasmedge-core
    runs-on: ubuntu-latest
    container:
      image: wasmedge/wasmedge:ubuntu2004_x86_64

    steps:
    - uses: actions/checkout@v2

    - name: Install clang
      if: ${{ contains(matrix.cc, 'clang') }}
      run: |
        apt update && apt install -y clang

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set Rust to required version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.50.0
        override: true

    - name: Install dependencies
      run: |
        apt update && apt install -y sudo
        npm install --unsafe-perm -g rustwasmc
        ln -s $(which node) /usr/local/bin/node
        ln -s $(which npm) /usr/local/bin/npm

    - name: Build wasmedge-core with ${{ matrix.cc }}
      uses: './.github/actions/build-from-source'
      with:
        cc: ${{ matrix.cc }}
        cxx: ${{ matrix.cxx }}

    - name: Test wasmedge-core built with ${{ matrix.cc }}
      run: |
        JOBS=max npm test
